version: 2
sphinx:
  configuration: docs/conf.py
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - method: pip
      path: .